version: '3.7'

services:
  api-storage:
    image: elasticsearch:7.3.1
    container_name: test-task-go-search-api-storage
    environment:
      - cluster.name=dev.local
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data:delegated"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail \"localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s\""]
      interval: 2s
      timeout: 2s
      retries: 5
  api:
    build:
      context: .
      dockerfile: build/Dockerfile.local
    container_name: test-task-go-search-api
    depends_on: ["api-storage"]
    links:
      - api-storage
    environment:
      - ALLOW_ORIGINS=http://localhost:8090
      - JWT_SECRET=local_dev_not_a_secret
      - ES_URL=http://api-storage:9200
      - ES_INDEX=products_local
    ports:
      - 8080:8080
    volumes:
      - "$PWD:/app:delegated"
      - "go-pkg:/go/pkg:delegated"
    working_dir: /app/cmd/api
    command: go run api.go
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/readiness"]
      interval: 2s
      timeout: 2s
      retries: 5
  api-swagger:
    image: swaggerapi/swagger-ui
    container_name: test-task-go-search-api-swagger
    ports:
      - 8090:8080
    environment:
      - SWAGGER_JSON=/swagger-ui/swagger.yaml
    volumes:
      - "$PWD/pkg/api/swagger.yaml:/swagger-ui/swagger.yaml:delegated"
volumes:
  elasticsearch-data:
  go-pkg:
