openapi: "3.0.0"
info:
  version: 1.0.0
  title: Shorten API
  license:
    name: MIT
servers:
  - url: http://localhost:8084
    description: Development (docker)
  - url: http://localhost:8081
    description: Development
paths:
  /shorten:
    post:
      summary: "Shorten long URL into a short URL."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                longUrl:
                  type: string
      responses:
        '200':
          description: URL successfully shorten.
          content:
            application/json:
              schema:
                type: object
                required:
                  - shortUrl
                properties:
                  shortUrl:
                    type: string
        '500':
          $ref: '#/components/responses/InternalServerError'

  /actuator/health/liveness:
    get:
      summary: Liveness probe. If response it not OK - application should be restarted
      operationId: healthLiveness
      tags:
        - health
      responses:
        '200':
          description: Application is ok.
        '503':
          description: Application needs to be restarted.

  /actuator/health/readiness:
    get:
      summary: Readiness probe. If response it not OK - application is not ready to process requests.
      operationId: healthReadiness
      tags:
        - health
      responses:
        '200':
          description: Application ready to process requests.
        '503':
          description: Application is not ready to process requests.

components:
  responses:
    InternalServerError:
      description: Internal server error.
