version: '3.8'
services:
  api-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8090:8080
    environment:
      SWAGGER_JSON: /swagger.yaml
    volumes:
      - "$PWD/swagger.yaml:/swagger.yaml:delegated"
    depends_on:
      - api-load-balancer

  api-load-balancer:
    image: nginx:latest
    volumes:
      - ./build/lb.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "8085:8080"

  api:
    build:
      context: .
      dockerfile: build/Dockerfile.local
    environment:
      KGS_ZOOKEEPER_CONNECT_STRING: zoo1:2181,zoo2:2181,zoo3:2181
    ports:
      - 5005-5105:5005
    volumes:
      - maven_repo:/root/.m2/repository
      - "$PWD:/app:delegated"
    working_dir: /app
    command: mvn spring-boot:run -DbuildDirectory=../target -Dspring-boot.run.jvmArguments="-Dlogging.level.com.ewgra=DEBUG -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health/readiness"
      interval: 2s
      timeout: 2s
      retries: 5

  zoo1:
    image: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    ports:
      - 2181:2181

  zoo2:
    image: zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    ports:
      - 2182:2181

  zoo3:
    image: zookeeper
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    ports:
      - 2183:2181

volumes:
  maven_repo:
