# FIXME XXX: check me
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Tiny URL User API
  license:
    name: MIT
servers:
  - url: http://localhost:8081
paths:
  /shorten:
    post:
      summary: "Shorten long URL into a tiny URL. FIXME XXX: rate limiter response"
      responses:
        '200':
          description: URL successfully shorten.
          content:
            application/json:
              schema:
                type: object
                required:
                  - shortUrl
                properties:
                  tinyUrl:
                    type: string
        '500':
          $ref: '#/components/responses/InternalServerError'

  /health/liveness:
    get:
      summary: Liveness probe. If response it not OK - application should be restarted
      operationId: healthLiveness
      tags:
        - health
      responses:
        '200':
          description: Application is ok.
        '503':
          description: Application needs to be restarted.

  /health/readiness:
    get:
      summary: Readiness probe. If response it not OK - application is not ready to process requests.
      operationId: healthReadiness
      tags:
        - health
      responses:
        '200':
          description: Application ready to process requests.
        '503':
          description: Application is not ready to process requests.

components:
  responses:
    InternalServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            type: object
            required:
              - success
              - message
            properties:
              success:
                type: boolean
                default: false
              message:
                type: string
