version: '3.7'

services:
  time-service:
    container_name: php-test-task-time-service
    build:
      context: .
      dockerfile: build/Dockerfile-local
    environment:
      - CORS_ALLOW_ORIGIN=*
    volumes:
      - '$PWD:/app:delegated'
    ports:
      - 8080:8000
    command: ["symfony", "server:start"]

  time-service-api-swagger:
    image: swaggerapi/swagger-ui
    container_name: php-test-task-time-service-swagger
    ports:
      - 8090:8080
    environment:
      - SWAGGER_JSON=/swagger.yaml
    volumes:
      - "$PWD/swagger.yaml:/swagger.yaml"