security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        api_users_in_memory:
            memory:
                users:
                    test:
                        password: test
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            http_basic:
                provider: api_users_in_memory
        api:
            pattern: ^/
            stateless: true
            http_basic:
                provider: api_users_in_memory
