version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: build/Dockerfile.local
    container_name: system-design-moderation-queue-api
    links:
      - rabbitmq
      - redis
    environment:
      - ALLOW_ORIGINS=http://localhost:8090
      - REDIS_ADDR=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - 8080:8080
    volumes:
      - "$PWD:/app:delegated"
      - "go-pkg:/go/pkg:delegated"
    working_dir: /app/cmd/api
    command: go run api.go
    healthcheck:
      test: "curl -f http://localhost:8080/health/readiness"
      interval: 2s
      timeout: 2s
      retries: 5
  api-swagger:
    image: swaggerapi/swagger-ui
    container_name: system-design-moderation-queue-api-swagger
    ports:
      - 8090:8080
    environment:
      - SWAGGER_JSON=/swagger-ui/swagger.yaml
    volumes:
      - "$PWD/pkg/api/swagger.yaml:/swagger-ui/swagger.yaml:delegated"
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: system-design-moderation-queue-rabbitmq
    volumes:
      - "rabbitmq:/data:delegated"
  redis:
    image: redis
    container_name: system-design-moderation-queue-redis
    volumes:
      - "redis:/data:delegated"

volumes:
  rabbitmq:
  redis:
  go-pkg: