version: '3.8'
services:
  user-app:
    image: nginx:latest
    environment:
      - API_URL=http://localhost:8081
    volumes:
      - ./user-app/nginx.template:/etc/nginx/templates/app.conf.template:ro
      - ./user-app/www:/www/data:ro
    ports:
      - "8080:8080"
