version: '3.8'
services:
  shorten-app:
    image: nginx:latest
    environment:
      API_URL: http://localhost:8084
    volumes:
      - ./shorten-app/nginx.template:/etc/nginx/templates/app.conf.template:ro
      - ./shorten-app/www:/www/data:ro
    ports:
      - "8080:8080"
    depends_on:
      - shorten-api-load-balancer

  shorten-api-api-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8090:8080
    environment:
      SWAGGER_JSON: /swagger.yaml
    volumes:
      - ./shorten-api/swagger.yaml:/swagger.yaml:delegated
    depends_on:
      - shorten-api-load-balancer

  shorten-api-load-balancer:
    image: nginx:latest
    volumes:
      - ./build/shorten-api-lb.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shorten-api
    ports:
      - "8084:8081"

  shorten-api:
    build:
      context: .
      dockerfile: build/Dockerfile.local
    depends_on:
      - key-generation-service-load-balancer
      - postgres
    ports:
      - 5005-5105:5005
    environment:
      SHORTEN_API_POSTGRES_URL: jdbc:postgresql://postgres:5432
      SHORTEN_API_KEY_GENERATION_SERVICE_URL: http://key-generation-service-load-balancer:8080
      SHORTEN_API_KEY_GENERATION_SERVICE_TEST_URL: http://key-generation-service-test:8080
      SHORTEN_API_VISITOR_APP_URL: http://localhost:8089
    volumes:
      - maven_repo:/root/.m2/repository
      - ./shorten-api:/app:delegated
    working_dir: /app
    command: mvn spring-boot:run -DbuildDirectory=../target -Dspring-boot.run.jvmArguments="-Dlogging.level.com.ewgra=DEBUG -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    healthcheck:
      test: "curl -f http://localhost:8081/actuator/health/readiness"
      interval: 2s
      timeout: 2s
      retries: 5

  key-generation-service-load-balancer:
    image: nginx:latest
    volumes:
      - ./build/key-generation-service-lb.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - key-generation-service

  key-generation-service:
    image: ewgra/key_generation_service:0.0.3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KGS_ZOOKEEPER_CONNECT_STRING: zoo1:2181,zoo2:2181,zoo3:2181
      KGS_ZOOKEEPER_NODE: /key_generation_service_counter
      KGS_COUNTER_RANGE_CAPACITY: 100
    ports:
      - 8095:8080

  key-generation-service-test:
    image: ewgra/key_generation_service:0.0.3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      KGS_ZOOKEEPER_CONNECT_STRING: zoo1:2181,zoo2:2181,zoo3:2181
      KGS_ZOOKEEPER_NODE: /counter-test
      KGS_COUNTER_RANGE_CAPACITY: 3
    ports:
      - 8096:8080
    healthcheck:
      test: "wget http://localhost:8080/actuator/health/readiness -q -O - > /dev/null 2>&1"
      interval: 2s
      timeout: 2s
      retries: 5

  zoo1:
    image: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  visitor-app-load-balancer:
    image: nginx:latest
    volumes:
      - ./build/visitor-app-lb.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - visitor-app
    ports:
      - "8089:8085"

  visitor-app:
    build:
      context: .
      dockerfile: build/Dockerfile.local
    depends_on:
      - postgres
      - redis
    ports:
      - 5106-5205:5005
    environment:
      VISITOR_APP_REDIS_HOST: redis
      VISITOR_APP_POSTGRES_URL: jdbc:postgresql://postgres:5432
    volumes:
      - maven_repo:/root/.m2/repository
      - ./visitor-app:/app:delegated
    working_dir: /app
    command: mvn spring-boot:run -DbuildDirectory=../target -Dspring-boot.run.jvmArguments="-Dlogging.level.com.ewgra=DEBUG -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    healthcheck:
      test: "curl -f http://localhost:8085/actuator/health/readiness"
      interval: 2s
      timeout: 2s
      retries: 5

  redis:
    build:
      context: .
      dockerfile: build/Dockerfile.redis.local
    ports:
      - 6379:6379

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: G3sfF7@tFd#
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  maven_repo:
  postgres-data:
