name: Continious integration

on: [push, pull_request]

jobs:
  ci:
    defaults:
      run:
        working-directory: go/search_api
    if: github.repository == 'ewgra/test_tasks'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15.4'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
          make lint
      - run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Test
        env:
          ES_URL: http://localhost:9200
          WAIT_HOSTS: localhost:9200
        run: |
          wget https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait -O wait && chmod +x wait
          docker-compose up -d api-storage
          ./wait
          curl http://localhost:9200
          make test
          docker-compose stop
