name: System design - Tiny URL - CI

on: [push, pull_request]

jobs:
  ci:
    defaults:
      run:
        working-directory: system_design/tinyurl
    if: github.repository == 'ewgra/test_tasks'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Lint
        run: |
          make lint
      - run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Test
        run: |
          docker-compose up -d
          echo dc started
          timeout 120 bash -c 'until docker-compose ps shorten-api | grep -q \(healthy\); do sleep 2; done' || (docker-compose ps && false)
          timeout 120 bash -c 'until docker-compose ps visitor-app | grep -q \(healthy\); do sleep 2; done' || (docker-compose ps && false)
          make test
          docker-compose stop
