name: System design - Key Generation Service- CI

on: [push, pull_request]

jobs:
  ci:
    defaults:
      run:
        working-directory: system_design/key_generation_service
    if: github.repository == 'ewgra/test_tasks'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Lint
        run: |
          make lint
      - run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Test
        run: |
          docker-compose up -d
          timeout 120 bash -c 'until docker-compose ps api | grep -q \(healthy\); do sleep 2; done' || false
          docker-compose exec -T api make test
          docker-compose stop
